automounter/src/automounter - Add a revisiting run to track label changes _after_ deleting old media links - Add a iso9660 detector that simply assumes acdN and cdN devices are optical   disc drives and treats them accordingly - Use stderr for warnings and errors
automounter/src/devd.conf
- A complete rewrite, now autodetects the appearance and disappearance of all
  md, ad, acd, ada, da and cd devices

automounter/src/automounter.8
- Follow changes (new features etc.)

automounter/src/automounter.conf.5
- Follow changes

automounter/CHANGES
- Record changes

diff --git a/automounter/src/automounter b/automounter/src/automounter
--- a/automounter/src/automounter
+++ b/automounter/src/automounter
@@ -21,7 +21,7 @@
 # THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #
 
-version=1.4.1
+version=1.4.2
 
 # AMD parameters
 a="%%RUN%%/automounter.amd"
@@ -111,10 +111,13 @@ timeout=10
 # to ensure that geom knows about new labels.
 update_delay=2
 
-# If set glabel file system detection is turned off.
+# If set to 1 glabel file system detection is turned on.
 detect_glabel=1
 
-# If set probe file system detection is turned off.
+# If set to 1 iso9660 hard coding for devices is turned on.
+detect_iso9660=1
+
+# If set to 1 probe file system detection is turned on.
 detect_probe=1
 
 # The default mount options.
@@ -129,6 +132,9 @@ evil_fuse=0
 
 # A comma separated list of file system types to probe geom providers for.
 probe_types=ufs,msdosfs,iso9660,ntfs,ext2fs
+
+# A comma separated list of device patterns that are hardcoded to iso9660.
+iso9660_devs="acd*,cd*"
 
 # Config file.
 config="%%PREFIX%%/etc/automounter.conf"
@@ -354,6 +360,43 @@ checkBlacklists() {
 	fi
 }
 
+#
+# This checks whether a revisit after cleanup is needed, because the device
+# was previously discovered with a different label.
+#
+# @param 1
+#	The name of the detector.
+# @param 2
+#	Set this if it is the revisit.
+# @param device
+#	The name of the device
+# @param label
+#	The label of the current device
+# @param revisit
+#	Add the detector if a second update run will be required to track a
+#	label change.
+# @return
+#	0 (true)	if a revisit is required
+#	1 (false)	otherwise
+#
+revisitNeeded() {
+	test -n "$2" && return 1
+	
+	# If this was alredy discovered with a different label,
+	# call for a revisit after the cleanup phase.
+	if /usr/bin/grep -q "^$device;" "$oldnodes" \
+		&& ! /usr/bin/grep -qFx "$device;$label" "$oldnodes"
+	then
+		# If not yet in the revisit list, add this detector.
+		if [ "$revisit" = "${revisit%$1}" ]; then
+			revisit="$revisit${revisit:+$IFS}$1"
+		fi
+		return 0
+	fi
+
+	return 1
+}
+
 # This function recors a node, creates the map file entry and calls
 # createLinks. The idea is to separate this code from the device discovery
 # code in the update() function.
@@ -480,10 +523,15 @@ mountedDetect() {
 #
 # Detect labeled devices and call writeNode().
 #
+# @param 1
+#	If set this is considered a revisit.
 # @param devices_blacklist
 #	A list of glob patterns to check the devices against.
 # @param nodes_blacklist
 #	A list glob patterns to check label nodes against.
+# @param revisit
+#	Add glabel if a second update run will be required
+#	to track a label change.
 #
 glabelDetect() {
 	# Check whether glabel based file system discovery has been disabled.
@@ -527,8 +575,12 @@ glabelDetect() {
 		# Finally we can set up a mount.
 		label="$line"
 
-		# This is in the list of already probed devices.
-		if /usr/bin/grep -qFx "$label" "$probed"; then
+		# This is in the list of already probed devices. Do not check
+		# the device node to be able to follow label changes.
+		# Instead check for the device in the list of already
+		# discovered nodes.
+		if /usr/bin/grep -qFx "$label" "$probed" \
+			|| /usr/bin/grep -q "^$device;" "$nodes"; then
 			continue
 		fi
 
@@ -536,7 +588,89 @@ glabelDetect() {
 		case "$label" in
 		*id/*)
 			continue
+		;;
 		esac
+
+		# Record the device to keep the following detectors from
+		# probing.
+		echo "$device" >> "$probed"
+
+		# If this was alredy discovered with a different label, e.g.
+		# because the label took too long to be discovered or was
+		# changed, call for a revisit after the cleanup phase.
+		if revisitNeeded glabel "$1"; then
+			continue
+		fi
+
+		# Write the node.
+		writeNode "$device" "$label"
+
+		# Append to the list of already probed devices.
+		echo "$label" >> "$probed"
+	done
+}
+
+#
+# Detect iso9660 devices without a disk or label and call writeNode().
+#
+# @param 1
+#	If set this is considered a revisit.
+# @param devices_blacklist
+#	A list of glob patterns to check the devices against.
+# @param nodes_blacklist
+#	A list glob patterns to check label nodes against.
+# @param revisit
+#	Add iso9660 if a second update run will be required to track the
+#	disappearance of a label.
+#
+iso9660Detect() {
+	# Check whether iso9660 hard coding has been disabled.
+	test "$detect_iso9660" != "1" && return 0
+
+	local devices device label dev_pattern
+
+	# Create a list of devices.
+	devices="$(
+		/usr/sbin/gstat -b -I0 | \
+		/usr/bin/tail -n +3 | \
+		/usr/bin/sed -E 's/([[:space:]]+[0-9.]+){9}[[:space:]]*//' | \
+		/usr/bin/grep -v '/'
+	)"
+
+	# Change the iso9660_devs format into something that can be used in a
+	# case statement.
+	dev_pattern="$(
+		echo "$iso9660_devs" | /usr/bin/sed -E \
+			-e 's/^[[:space:]]*,//' -e 's/,[[:space:]]*$//' \
+			-e 's/,/|/g' -e 's,([[:space:]\\]),\\\1,g'
+	)"
+
+	# Add new mounts.
+	for device in $devices; do
+		# This is in the list of already probed devices.
+		if /usr/bin/grep -qFx "$device" "$probed"; then
+			continue
+		fi
+
+		# Skip if the device is not in the pattern list.
+		eval "
+			case '$device' in
+				$dev_pattern)
+					# pass
+				;;
+				*)
+					continue
+				;;
+			esac
+		"
+
+		label="iso9660/$device"
+
+		# If this was previously discovered with a label, call for
+		# a revisit after the cleanup phase.
+		if revisitNeeded iso9660 "$1"; then
+			continue
+		fi
 
 		# Write the node.
 		writeNode "$device" "$label"
@@ -549,10 +683,15 @@ glabelDetect() {
 #
 # Detect labeled devices and call writeNode().
 #
+# @param 1
+#	If set this is considered a revisit.
 # @param devices_blacklist
 #	A list of glob patterns to check the devices against.
 # @param nodes_blacklist
 #	A list glob patterns to check label nodes against.
+# @param revisit
+#	Add probe if a second update run will be required to track the
+#	disappearance of a label or a file system type change.
 #
 probeDetect() {
 	# Check whether probing based file system discovery has been disabled.
@@ -599,13 +738,19 @@ probeDetect() {
 				options="$(eval "echo \"\$${type}_options\"")"
 			fi
 
-			# Add the label to the list of probed devices.
-			echo "$label" >> "$probed"
-
 			# Try to mount the device.
 			if probeMount "$type" "$device"; then
 				# Unmount the probe.
 				probeUnmount
+
+				# If this was previously discovered with a
+				# label, or a different file system type, call
+				# for a revisit after the cleanup phase.
+				if revisitNeeded probe "$1"; then
+					# Skip the following probes on this
+					# device.
+					break
+				fi
 
 				# Write the node.
 				writeNode "$device" "$label"
@@ -616,6 +761,9 @@ probeDetect() {
 				# Skip the following probes on this device.
 				break
 			fi
+
+			# Add the label to the list of probed devices.
+			echo "$label" >> "$probed"
 		done
 	done
 
@@ -635,7 +783,7 @@ probeDetect() {
 #
 update() {
 	local device line partitions label type options
-	local hash owner mode key detector
+	local hash owner mode key detector revisit
 	local devices_blacklist nodes_blacklist
 
 	# Don't do anything if amd is not running.
@@ -669,7 +817,8 @@ update() {
 	)"
 
 	# Run detectors.
-	for detector in mounted glabel probe mounted; do
+	revisit=
+	for detector in mounted glabel iso9660 probe mounted; do
 		/bin/sync
 		${detector}Detect
 	done
@@ -681,6 +830,12 @@ update() {
 
 		# Remove the stale media links.
 		rmLinks "$label" "$device"
+	done
+
+	# Revisit detectors requesting it.
+	for detector in $revisit; do
+		/bin/sync
+		${detector}Detect revisit
 	done
 
 	# Finally reload amd map.
@@ -889,7 +1044,7 @@ list() {
 	# but the probabality that bogus output will appear is rather low
 	# and not aquiring the lock allows everyone to use the list command.
 	if [ -e "$lock" ]; then
-		echo "Locked."
+		echo "Locked." 1>&2
 		return $ERR_LIST_LOCKED
 	fi
 
@@ -1093,7 +1248,7 @@ umount() {
 	# If the device is missing (i.e. it was removed while being mounted),
 	# force umount.
 	if [ ! -e "$devfs/$device" ]; then
-		echo "automounter: Force unmounting missing <$label> from <$device>"
+		echo "automounter: Force unmounting missing <$label> from <$device>" 1>&2
 		# Schedule an update.
 		$0 update 1 &
 		exec /sbin/umount -f "$mountdir/$label" 2> "$devfs/null"
@@ -1115,15 +1270,6 @@ case "$1" in
 				$2 "$3"
 				return
 			;;
-			*)
-				cat << HERE-DOC
-automounter: unknown directive '$2'.
-Usage:	automounter (start | update | list | mlist | stop)
-	automounter list [mounted | labels | keys | encrypted]
-	automounter mlist [mounted | llinks | dlinks]
-HERE-DOC
-				return $ERR_CMD_UNKNOWN
-			;;
 		esac
 	;;
 	list | mlist | mount)
@@ -1134,18 +1280,27 @@ HERE-DOC
 		# Unmounts should not happen during updates.
 		exec /usr/bin/lockf -st 0 "$lock" $0 locked "$@"
 	;;
-	*)
+	start | update | stop)
 		/usr/bin/lockf -st "$timeout" "$lock" $0 locked "$@"
 		status=$?
 		case $status in
-			0 | $ERR_CMD_UNKNOWN | $ERR_NOT_STARTED | $ERR_MOUNT_FS_MISSING | $ERR_UMOUNT_ACTIVE)
+			0 | $ERR_NOT_STARTED | $ERR_MOUNT_FS_MISSING | $ERR_UMOUNT_ACTIVE)
 				# Silent success/fail
 			;;
 			$EX_USAGE | $EX_SOFTWARE | $EX_OSERR | $EX_CANTCREAT | $EX_TEMPFAIL)
-				echo "automounter: Lock could not be aquired:" "$@"
+				echo "automounter: Lock could not be aquired:" "$@" 1>&2
 			;;
 		esac
 		return $status
+	;;
+	*)
+		cat << HERE-DOC
+automounter: unknown directive '$1'.
+Usage:	automounter (start | update | list | mlist | stop)
+	automounter list [mounted | labels | keys | encrypted]
+	automounter mlist [mounted | llinks | dlinks]
+HERE-DOC
+		return $ERR_CMD_UNKNOWN
 	;;
 esac
 
